### ISSUE TITLE
データが存在しない年度を参照してから他年度を参照すると表示が更新されない

### ISSUE THREAD

**Issue by eggplants** [argonism/KlisStatistics#12]
例:
- 多変量解析の2014年度(未開設)を開いてから同科目の2018年度を開く

なお、他科目を開くと再表示される。

**Comment by argonism** [comment]
commit: ec1d52f7346aebb77b3d8b79147fda324c191ca1
で対応したので、よければご確認を...
（反映を確認した後で)

**Comment by eggplants** [comment]
![Peek 2020-01-23 17-32](https://user-images.githubusercontent.com/42153744/72968216-6137e380-3e06-11ea-8bbf-a3477b86e78e.gif)
うーん、最高！
