### ISSUE TITLE
GitHubリンクの追加

### ISSUE THREAD

**Issue by eggplants** [argonism/KlisStatistics#14]
フッターかヘッダーに
- リポジトリ
  - https://github.com/argonism/KlisStatistics/
  - [rcaferati/github-fork](https://github.com/rcaferati/github-fork)を使用しても良いかも
- 開発者
  - https://github.com/argonism/
- 開発年間
  - 2019-2020
- データソース
  - https://klis.tsukuba.ac.jp/school_affairs.html

の情報を追加するといいかもです
(不必要かもなんでその場合はcloseします！)

**Comment by argonism** [comment]
いい提案だと思います！情報源見やすくした方が、他に何か作りたい人の参考になるしね

**Comment by argonism** [comment]
レイアウトビミョいけどフッターに追加しました

**Comment by eggplants** [comment]
うーん最高
