### ISSUE TITLE
データの母数表示

### ISSUE THREAD

**Issue by eggplants** [argonism/KlisStatistics#8]
グラフ、アンケートそれぞれの母数、回答者数を表示してほしい。

**Comment by argonism** [comment]
あぁーそっか。確かに欲しいね

**Comment by argonism** [comment]
9324c2eba941cbda1a09e2dd3c322340aa863b02
で対応しました（遅れてゴメス

**Comment by eggplants** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by eggplants** [comment]
LGTM
